### PR TITLE
docs-33 - update `Contribute to Docs` link to open within same window

### PR DESCRIPTION
**Pull request by jcstein**

### CODE REVIEW

**Comment by jcstein** [comment]
Are there any issues with this PR?

**Comment by jcstein** [comment]
@raproid @ddocs @ankrzuke

**Comment by jcstein** [comment]
Btw if I funked this up, this was the only edit!

**Comment by raproid** [comment]
oh, I missed this pr. will review a little bit later

**Comment by raproid** [comment]
please make me a reviewer next time. thx in advance

**Pull request merged**
