### PR TITLE
docs: add movie voting tutorial

### PR DESCRIPTION
**Pull request by gabor-boros**
**title**

How to create a voting system on Ethereum using web3

**Content description**

This tutorial is about implementing a simple movie voting system based on blockchain.

**Tag your content**

* Web3.js
* Truffle
* Ganache
* Ankr Platform

**Publication**

N/A

**Skill level**

Beginner/Intermediate

### CODE REVIEW

**Comment by ddocs** [comment]
This is great Gabor, thanks for submitting. We'll review it asap. :)

**Comment by prtkgpt** [comment]
Thank you, Gabor.

**Comment by gabor-boros** [comment]
@ddocs @prtkgpt Thank you! 

Since there were no directories previously to store images, I tried to create a somewhat sustainable and organized structure. Please let me know if that should be changed. 😇

**Review by corey-ankr — COMMENTED** [review]
Great content @gabor-boros! Thanks for contributing. We will perform the final review for approval very soon, and reach back out to you with an update.

**Pull request merged**
