### PR TITLE
fixed typo for InternalTransactionsByBlockNumber

### PR DESCRIPTION
**Pull request by avious00**

### CODE REVIEW

**Comment by avious00** [comment]
fyi @galleon8 @raproid

**Comment by raproid** [comment]
Hey,

Thank you!

Two things, tho:
1. We don't pr directly into`main`, we pr into `stage`.
2. In the process of fixing the typo, you also deleted a closing `

Please open another pr into the stage branch and restore the missing `
I'll be happy to merge it

**Comment by raproid** [comment]
assumed you were busy and fixed it by hand: https://github.com/Ankr-network/ankr-docs/pull/1551

**Comment by raproid** [comment]
thanks again!

**Comment by avious00** [comment]
@raproid appreciate you resolving this!

**Pull request closed without merging**
